language: java

jdk:
  - openjdk8
  - openjdk12

cache:
  directories:
    - $HOME/.gradle # Gradle build cache

before_install: chmod +x ./gradlew

jobs:
  include:
    - stage: deploy
      script: ./gradlew publish